<?php
if (session_status() === PHP_SESSION_NONE) session_start();
require_once __DIR__ . '/portal.php';
$roles = ['Rural Health Midwife' => ['MIDWIFE', 'MidwifeDashboard.php'], 'Public Health Nurse' => ['NURSE', 'NurseDashboard.php'], 'Medical Technologist' => ['MEDTECH', 'MedTechDashboard.php'], 'Sanitary Inspector' => ['SANITARY_INSPECTOR', 'SanitaryDashboard.php'], 'Administrative Staff' => ['ADMIN_STAFF', 'AdminStaffDashboard.php']];
$error = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $role = $_POST['role'] ?? ''; $email = trim($_POST['email'] ?? ''); $password = $_POST['password'] ?? '';
    if (!isset($roles[$role]) || !$email || !$password) $error = 'Enter your role, email address, and password.';
    elseif (empty($pdo)) $error = 'The database is unavailable. Please try again later.';
    else try {
        [$staffType, $route] = $roles[$role];
        $statement = $pdo->prepare('SELECT u.id AS user_id, u.email, u.password_hash, u.first_name, u.last_name, s.id AS staff_id, s.staff_type FROM users u INNER JOIN staff s ON s.user_id = u.id WHERE u.email = :email AND u.is_active = 1 AND s.is_active = 1 AND s.staff_type = :staff_type LIMIT 1');
        $statement->execute(['email' => $email, 'staff_type' => $staffType]); $staff = $statement->fetch();
        if (!$staff || !password_verify($password, $staff['password_hash'])) $error = 'Invalid staff credentials or selected role.';
        else { $_SESSION['rhu_staff_login'] = ['id' => (int)$staff['user_id'], 'staff_id' => (int)$staff['staff_id'], 'email' => $staff['email'], 'role' => $role, 'staff_type' => $staff['staff_type'], 'name' => trim($staff['first_name'] . ' ' . $staff['last_name'])]; portalAudit($pdo, (int)$staff['user_id'], 'RHU staff login', 'staff', (int)$staff['staff_id']); header('Location: ' . $route); exit; }
    } catch (PDOException $exception) { error_log('RHU staff login: ' . $exception->getMessage()); $error = 'Unable to sign in right now. Please try again later.'; }
}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>RHU Staff Portal</title><script src="https://cdn.tailwindcss.com"></script></head>
<body class="flex min-h-screen items-center justify-center bg-gradient-to-br from-blue-50 via-white to-indigo-50 px-4 py-8"><main class="w-full max-w-md"><header class="mb-8 text-center"><a href="LandingPage.php" class="inline-flex items-center gap-2"><span class="text-4xl text-red-600">♥</span><span class="text-3xl font-bold">RedPulse RHU</span></a><h1 class="mt-4 text-2xl font-bold text-gray-900">⚕ RHU Staff Portal</h1><p class="text-sm text-gray-500">Nasugbu Rural Health Unit</p></header><section class="rounded-2xl border border-gray-100 bg-white p-8 shadow-xl"><?php if ($error): ?><div class="mb-5 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700"><?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8') ?></div><?php endif; ?><form method="post" class="space-y-5"><label class="block text-sm font-semibold text-gray-700">Staff Role<select name="role" class="mt-2 w-full rounded-lg border border-gray-300 px-4 py-3"><?php foreach ($roles as $role => $details): ?><option<?= (($_POST['role'] ?? '') === $role) ? ' selected' : '' ?>><?= htmlspecialchars($role, ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></label><label class="block text-sm font-semibold text-gray-700">RHU Email Address<input required name="email" type="email" value="<?= htmlspecialchars($_POST['email'] ?? '', ENT_QUOTES, 'UTF-8') ?>" class="mt-2 w-full rounded-lg border border-gray-300 px-4 py-3" placeholder="yourname@nasugbu.rhu.ph"></label><label class="block text-sm font-semibold text-gray-700">Password<input required name="password" type="password" class="mt-2 w-full rounded-lg border border-gray-300 px-4 py-3" placeholder="Enter your password"></label><button class="w-full rounded-lg bg-gradient-to-r from-blue-600 to-blue-700 py-3 font-semibold text-white shadow-lg">Sign In to RHU Portal</button></form><aside class="mt-5 flex gap-2 rounded-lg border border-blue-100 bg-blue-50 p-3 text-xs text-blue-700"><span>♢</span>Access is restricted to authorized Nasugbu RHU personnel only. All sessions are logged and audited.</aside></section><footer class="mt-6 space-y-3 text-center text-sm"><p><a href="RHUAdminLogin.php" class="font-semibold text-gray-500">RHU Admin</a> <span class="mx-2 text-gray-300">|</span><a href="BHWLogin.php" class="font-semibold text-gray-500">BHW Portal</a></p><p class="text-xs text-gray-400">Resident? <a href="ResidentLogin.php" class="font-semibold text-emerald-600">Go to Resident Portal</a></p><a href="LandingPage.php" class="text-gray-400">← Back to Home</a></footer></main></body></html>
